packages:
  - 'packages/*'

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true

catalog:
  eslint: '^9.17.0'
  typescript: '^5.7.2'
  typescript-eslint: '^8.19.0'
  cheerio: '^1.0.0'
  vitest: '^3.0.0'
